# Generated by Django 3.0.2 on 2020-01-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stes_test', '0002_student_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='alt_phone_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='district',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
    ]
